[package]
name = "integration_test"
version = "0.1.0"
authors = ["Steven Roose <steven@stevenroose.org>"]
edition = "2018"

[dependencies]
ord-bitcoincoret4-rpc = { path = "../client" }
bitcoint4 = { version = "0.30.2", features = ["serde", "rand"] }
lazy_static = "1.4.0"
log = "0.4"
